# Generated by Django 2.2.1 on 2019-05-10 21:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Distelec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codele', models.CharField(max_length=6)),
                ('provincia', models.CharField(max_length=10)),
                ('canton', models.CharField(max_length=20)),
                ('distrito', models.CharField(max_length=34)),
            ],
        ),
        migrations.CreateModel(
            name='Padron_electoral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=9)),
                ('codelec', models.CharField(max_length=6)),
                ('sexo', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)])),
                ('fecha_caducidad', models.CharField(max_length=8)),
                ('junta', models.CharField(max_length=5)),
                ('nombre', models.CharField(max_length=30)),
                ('primer_apellido', models.CharField(max_length=26)),
                ('segundo_apellido', models.CharField(max_length=26)),
            ],
        ),
    ]
