# Generated by Django 2.2.1 on 2019-05-20 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distelec',
            name='distrito',
            field=models.CharField(max_length=40),
        ),
    ]
