# Generated by Django 2.2.1 on 2019-05-20 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20190520_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distelec',
            name='distrito',
            field=models.CharField(max_length=34),
        ),
    ]
