# Generated by Django 2.2.1 on 2019-06-19 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importcrdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='padronelectoral',
            name='junta',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='padronelectoral',
            name='nombre_completo',
            field=models.CharField(max_length=150),
        ),
    ]
