# Generated by Django 2.2.1 on 2019-05-15 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importcrdata', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distelec',
            name='id',
        ),
        migrations.AlterField(
            model_name='distelec',
            name='codelec',
            field=models.CharField(max_length=6, primary_key=True, serialize=False),
        ),
    ]
