# Generated by Django 2.2.1 on 2019-05-15 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('importcrdata', '0002_auto_20190515_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='padronelectoral',
            name='codelec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='importcrdata.Distelec'),
        ),
    ]
