# Generated by Django 2.2.1 on 2019-05-15 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importcrdata', '0003_auto_20190515_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='padronelectoral',
            name='id',
        ),
        migrations.AlterField(
            model_name='padronelectoral',
            name='cedula',
            field=models.CharField(max_length=9, primary_key=True, serialize=False),
        ),
    ]
